spring:
  datasource:
    url: jdbc:h2:mem:bank-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    #http://localhost:8081/h2
    console.enabled: true
    console.path: /h2

server:
  port: 8081

jwt:
  token:
    secret: finalprojectsber
    expired: 300000